name: Quiz project
on: push

jobs:
  first:
    name: Install ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: check out repo
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo apt install python3-pip
      - name: Requirements install
        run: pip install -r quiz-p16/requirements.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: QuizProject.settings.local

        run: python manage.py test
        working-directory: quiz-p16/